# Generated by Django 3.2.4 on 2021-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210512_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickup_available',
            field=models.BooleanField(default=False),
        ),
    ]
