# Generated by Django 3.2.4 on 2021-07-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
